name: Common Configuration

on:
  workflow_dispatch:
  push: # needed?

jobs:
  common-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable # only for jobs that contains 'tests'
        run: |
          if [[ "${{ github.job }}" == *"tests"* ]]; then
            chmod +x ./gradlew
          fi
