name: Send to Main

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew clean unitTest

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew
      - name: Run integration tests
        run: ./gradlew clean integrationTest

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew
      - name: Start Application
        run: |
          ./gradlew bootRun &
          echo "Application started"
          sleep 10
      - name: Run API tests
        run: ./gradlew clean apiTest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew
      - name: Run checkstyle
        run: ./gradlew clean checkstyleMain checkstyleTest

  build_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/annasjoberg/singlaslant-individual
          flavor: |
            latest=auto  # Handle latest tag automatically
            prefix=pr-
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}, latest

  mock-deployment:
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - name: Mock Deployment
        run: |
          echo "ghcr.io/annasjoberg/singlaslant-individual:${{ steps.meta.outputs.tags }}"
          echo "ghcr.io/annasjoberg/singlaslant-individual:latest"
