name: Send to Staging

on:
  push:
    branches:
      - feat_*
      - bugfix_*
      - hotfix_*

jobs: 
  unit-tests:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with: 
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Make Gradlew Executable
      run: |
          chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew unitTest

  integration-tests:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Make Gradlew Executable
      run: |
        chmod +x ./gradlew
    - name: Run integration tests
      run: ./gradlew integrationTest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: |
          chmod +x ./gradlew
      - name: Run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

  build_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Build and Push Test Image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/annasjoberg/singlaslant-individual-test:${{ env.branch }} -f Dockerfile .
          echo "Test image built and pushed"
      - name: Push image
        run: docker push ghcr.io/annasjoberg/singlaslant-individual-test:${{ env.branch }}

  mock-deployment: 
    runs-on: ubuntu-latest
    needs:   build_push_image
    steps:
    - name: Get branch name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    - name: Mock Deployment
      run: echo "ghcr.io/annasjoberg/singlaslant-individual-test:${{ env.branch }}"
