name: Send to Staging

on:
  push:
    branches:
      - feat_*
      - bugfix_*
      - hotfix_*

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable # only for jobs that contains 'tests'
        run: |
          chmod +x ./gradlew

  unit-tests:
    runs-on: ubuntu-latest
    needs: test-config
    steps:
      - name: Run unit tests
        working-directory: ${{ github.workspace }}
        run: ./gradlew unitTest

  integration-tests:
    runs-on: ubuntu-latest
    needs: test-config
    steps:
      - name: Run integration tests
        working-directory: ${{ github.workspace }}
        run: ./gradlew integrationTest

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Build image
        run: docker build -t ghcr.io/annasjoberg/singlaslant-individual:${{ env.branch }} -f Dockerfile .
      - name: Push image
        run: docker push ghcr.io/annasjoberg/singlaslant-individual:${{ env.branch }}

  fake-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Fake Deployment
        run: echo "ghcr.io/annasjoberg/singlaslant-individual:${{ env.branch }}"
